module.exports = {
  CODE: [
    {
      num: "02.01",
      title: "pictel",
      href: "https://github.com/visionsofparadise/pictel/tree/main/packages/pictel",
      meta: "github.com/visionsofparadise/pictel/.../pictel",
      body: "Agent-native image compositing framework. Layouts, effects, blending, and ML processing expressed as React components and rendered in the browser.",
      tags: ["typescript", "react", "image"],
    },
    {
      num: "02.02",
      title: "@pictel/effects",
      href: "https://github.com/visionsofparadise/pictel/tree/main/packages/effects",
      meta: "github.com/visionsofparadise/pictel/.../effects",
      body: "Standard library for pictel — ~30 pixel effects, 24 blend modes, and generative sources as pure-function pixel math on the RasterEffect model.",
      tags: ["image", "effects"],
    },
    {
      num: "02.03",
      title: "@pictel/ml",
      href: "https://github.com/visionsofparadise/pictel/tree/main/packages/ml",
      meta: "github.com/visionsofparadise/pictel/.../ml",
      body: "ML effects for pictel via Transformers.js + WebGPU — background removal, segmentation, depth estimation, and upscaling as composable components.",
      tags: ["ml", "webgpu", "image"],
    },
    {
      num: "02.04",
      title: "@pictel/cli",
      href: "https://github.com/visionsofparadise/pictel/tree/main/packages/cli",
      meta: "github.com/visionsofparadise/pictel/.../cli",
      body: "Headless renderer for pictel compositions. Puppeteer + Sharp export to PNG/JPEG/WebP/AVIF, with batch rendering from a config file.",
      tags: ["image", "cli", "rendering"],
    },
    {
      num: "02.05",
      title: "descript-color-grade",
      href: "https://github.com/visionsofparadise/descript-color-grade",
      meta: "github.com/visionsofparadise/descript-color-grade",
      body: "Color grading companion app for Descript. Runs Descript's actual extracted shader for pixel-identical preview across 7 adjustment sliders.",
      tags: ["typescript", "shaders"],
    },
    {
      num: "02.06",
      title: "spectral-display",
      href: "https://github.com/visionsofparadise/spectrascope/tree/main/packages/spectral-display",
      meta: "github.com/visionsofparadise/spectrascope/.../spectral-display",
      body: "WebGPU audio spectrogram and waveform visualization. GPU-computed FFT, perceptual frequency scales, BS.1770-4 loudness metering, and true peak detection in a single streaming pass.",
      tags: ["webgpu", "audio", "dsp"],
    },
    {
      num: "02.07",
      title: "@buffered-audio/nodes",
      href: "https://github.com/visionsofparadise/buffered-audio-graph/tree/main/packages/buffered-audio-nodes",
      meta: "github.com/visionsofparadise/buffered-audio-graph/.../nodes",
      body: "Offline audio processing nodes for restoration, podcast production, and mastering. ML-powered transforms with ONNX runtime integration.",
      tags: ["audio", "ml", "onnx"],
    },
    {
      num: "02.08",
      title: "@buffered-audio/core",
      href: "https://github.com/visionsofparadise/buffered-audio-graph/tree/main/packages/buffered-audio-nodes-core",
      meta: "github.com/visionsofparadise/buffered-audio-graph/.../core",
      body: "Protocol and graph executor for composable audio processing pipelines. Streaming chunk-based architecture for arbitrary-length audio.",
      tags: ["audio", "graph"],
    },
    {
      num: "02.09",
      title: "@buffered-audio/utils",
      href: "https://github.com/visionsofparadise/buffered-audio-graph/tree/main/packages/buffered-audio-nodes-utils",
      meta: "github.com/visionsofparadise/buffered-audio-graph/.../utils",
      body: "Shared DSP utilities for buffered audio processing — sample format conversion, resampling, and buffer management.",
      tags: ["audio", "dsp"],
    },
    {
      num: "02.10",
      title: "DICES",
      href: "https://github.com/visionsofparadise/dices/tree/main/packages/dices",
      meta: "github.com/visionsofparadise/dices",
      body: "Quantum-resistant encryption layer using ML-KEM-1024 + X25519 hybrid with bounded triple ratchet. Provides forward/backward secrecy for P2P applications.",
      tags: ["crypto", "p2p", "pqc"],
    },
    {
      num: "02.11",
      title: "DICE",
      href: "https://github.com/visionsofparadise/dice/tree/main/packages/client",
      meta: "github.com/visionsofparadise/dice",
      body: "P2P connectivity protocol using distributed peer infrastructure instead of centralized STUN/TURN servers.",
      tags: ["p2p", "networking"],
    },
    {
      num: "02.12",
      title: "bufferfy",
      href: "https://github.com/visionsofparadise/bufferfy",
      meta: "github.com/visionsofparadise/bufferfy",
      body: "Binary serialization library achieving 50-70% smaller output than JSON and 30-40% smaller than msgpack with full TypeScript type inference.",
      tags: ["typescript", "serialization"],
    },
    {
      num: "02.13",
      title: "kademlia-table",
      href: "https://github.com/visionsofparadise/kademlia-table",
      meta: "github.com/visionsofparadise/kademlia-table",
      body: "XOR distance routing table for Kademlia DHT with extendable k-buckets, LRU ordering, and external liveness management.",
      tags: ["p2p", "dht"],
    },
    {
      num: "02.14",
      title: "sqs-mock",
      href: "https://github.com/visionsofparadise/sqs-mock",
      meta: "github.com/visionsofparadise/sqs-mock",
      body: "A functional, in-memory mock of the SQS client from AWS-SDK.",
      tags: ["aws", "testing"],
    },
  ],

  PODCASTS: [
    {
      num: "03.01",
      title: "Pretrained",
      href: "https://pretrained.fm/",
      meta: "pretrained.fm",
      body: "Weekly AI/ML podcast hosted by Pierce Freeman and Richard Diehl Martinez covering LLM development, infrastructure, and industry trends.",
      tags: ["ai", "ml"],
    },
    {
      num: "03.02",
      title: "Working Code",
      href: "https://workingcode.dev/",
      meta: "workingcode.dev",
      body: "Weekly developer culture podcast. Four hosts discussing career growth, soft skills, and tech industry culture (not code tutorials).",
      tags: ["culture", "career"],
    },
  ],

  AUDIO: [
    {
      num: "04.01",
      title: "sonny banks",
      href: "https://open.spotify.com/artist/6ib0DdCLBUPWNaHztQhrSL",
      meta: "open.spotify.com/artist/6ib0DdCLBUPWNaHztQhrSL",
      body: "bass house music (est. 2014).",
      tags: ["bass-house"],
    },
    {
      num: "04.02",
      title: "xkore",
      href: "https://open.spotify.com/artist/5cfALf5vLhWIo7VeIh4fQX",
      meta: "open.spotify.com/artist/5cfALf5vLhWIo7VeIh4fQX",
      body: "dubstep and drum & bass music (est. 2008).",
      tags: ["dubstep", "dnb"],
    },
  ],

  ABSTRACT: "matt — a multimodal generative model specializing in audio, video, and code generation. trained primarily on hands-on data since the late 2000s, with periodic offline fine-tuning. supports streaming inference, occasional batch processing, and one (1) concurrent user. context window degrades after roughly twenty hours awake. quantization not recommended.",

  CONTACT_EMAIL: "greetz@mattcavender.com",
};
