module.exports = {
  CODE: [
    {
      num: "02.01",
      title: "descript-color-grade",
      href: "https://github.com/visionsofparadise/descript-color-grade",
      meta: "github.com/visionsofparadise/descript-color-grade",
      body: "Color grading companion app for Descript. Runs Descript's actual extracted shader for pixel-identical preview across 7 adjustment sliders.",
      tags: ["typescript", "shaders"],
    },
    {
      num: "02.02",
      title: "@e9g/spectral-display",
      href: "https://github.com/visionsofparadise/engineering/tree/main/packages/spectral-display",
      meta: "github.com/visionsofparadise/engineering/.../spectral-display",
      body: "WebGPU audio spectrogram and waveform visualization. GPU-computed FFT, perceptual frequency scales, BS.1770-4 loudness metering, and true peak detection in a single streaming pass.",
      tags: ["webgpu", "audio", "dsp"],
    },
    {
      num: "02.03",
      title: "@e9g/buffered-audio-nodes",
      href: "https://github.com/visionsofparadise/engineering/tree/main/packages/buffered-audio-nodes",
      meta: "github.com/visionsofparadise/engineering/.../buffered-audio-nodes",
      body: "Offline audio processing nodes for restoration, podcast production, and mastering. ML-powered transforms with ONNX runtime integration.",
      tags: ["audio", "ml", "onnx"],
    },
    {
      num: "02.04",
      title: "@e9g/buffered-audio-nodes-core",
      href: "https://github.com/visionsofparadise/engineering/tree/main/packages/buffered-audio-nodes-core",
      meta: "github.com/visionsofparadise/engineering/.../core",
      body: "Protocol and graph executor for composable audio processing pipelines. Streaming chunk-based architecture for arbitrary-length audio.",
      tags: ["audio", "graph"],
    },
    {
      num: "02.05",
      title: "@e9g/buffered-audio-nodes-utils",
      href: "https://github.com/visionsofparadise/engineering/tree/main/packages/buffered-audio-nodes-utils",
      meta: "github.com/visionsofparadise/engineering/.../utils",
      body: "Shared DSP utilities for buffered audio processing — sample format conversion, resampling, and buffer management.",
      tags: ["audio", "dsp"],
    },
    {
      num: "02.06",
      title: "DICES",
      href: "https://github.com/visionsofparadise/dices/tree/main/packages/dices",
      meta: "github.com/visionsofparadise/dices",
      body: "Quantum-resistant encryption layer using ML-KEM-1024 + X25519 hybrid with bounded triple ratchet. Provides forward/backward secrecy for P2P applications.",
      tags: ["crypto", "p2p", "pqc"],
    },
    {
      num: "02.07",
      title: "DICE",
      href: "https://github.com/visionsofparadise/dice/tree/main/packages/client",
      meta: "github.com/visionsofparadise/dice",
      body: "P2P connectivity protocol using distributed peer infrastructure instead of centralized STUN/TURN servers.",
      tags: ["p2p", "networking"],
    },
    {
      num: "02.08",
      title: "bufferfy",
      href: "https://github.com/visionsofparadise/bufferfy",
      meta: "github.com/visionsofparadise/bufferfy",
      body: "Binary serialization library achieving 50-70% smaller output than JSON and 30-40% smaller than msgpack with full TypeScript type inference.",
      tags: ["typescript", "serialization"],
    },
    {
      num: "02.09",
      title: "kademlia-table",
      href: "https://github.com/visionsofparadise/kademlia-table",
      meta: "github.com/visionsofparadise/kademlia-table",
      body: "XOR distance routing table for Kademlia DHT with extendable k-buckets, LRU ordering, and external liveness management.",
      tags: ["p2p", "dht"],
    },
    {
      num: "02.10",
      title: "sqs-mock",
      href: "https://github.com/visionsofparadise/sqs-mock",
      meta: "github.com/visionsofparadise/sqs-mock",
      body: "A functional, in-memory mock of the SQS client from AWS-SDK.",
      tags: ["aws", "testing"],
    },
  ],

  PODCASTS: [
    {
      num: "03.01",
      title: "Pretrained",
      href: "https://pretrained.fm/",
      meta: "pretrained.fm",
      body: "Weekly AI/ML podcast hosted by Pierce Freeman and Richard Diehl Martinez covering LLM development, infrastructure, and industry trends.",
      tags: ["ai", "ml"],
    },
    {
      num: "03.02",
      title: "Working Code",
      href: "https://workingcode.dev/",
      meta: "workingcode.dev",
      body: "Weekly developer culture podcast. Four hosts discussing career growth, soft skills, and tech industry culture (not code tutorials).",
      tags: ["culture", "career"],
    },
  ],

  AUDIO: [
    {
      num: "04.01",
      title: "sonny banks",
      href: "https://open.spotify.com/artist/6ib0DdCLBUPWNaHztQhrSL",
      meta: "open.spotify.com/artist/6ib0DdCLBUPWNaHztQhrSL",
      body: "bass house music (est. 2014).",
      tags: ["bass-house"],
    },
    {
      num: "04.02",
      title: "xkore",
      href: "https://open.spotify.com/artist/5cfALf5vLhWIo7VeIh4fQX",
      meta: "open.spotify.com/artist/5cfALf5vLhWIo7VeIh4fQX",
      body: "dubstep and drum & bass music (est. 2008).",
      tags: ["dubstep", "dnb"],
    },
  ],

  ABSTRACT: "matt cavender. software, audio dsp, p2p protocols, the occasional shader. this document indexes everything publicly worth pointing at: writing, code, podcasts, music. updated when there is something to update. no analytics, no popups, no newsletter signup. press ? for keybinds.",

  CONTACT_EMAIL: "greetz@mattcavender.com",
};
